### ISSUE TITLE
I think you're using some really old version of `crev`.

### ISSUE THREAD

**Issue by dpc** [bjorn3/crev-proofs#1]
Somewhere along the line `crev` was supposed to stop using padding for digests. I would advise upgrading and creating a new `Id`. This might or might not work in the future.

**Comment by bjorn3** [comment]
To be honest I was only experimenting with it for one day. (The day I opened https://github.com/dpc/crev/issues/63)

**Comment by bjorn3** [comment]
Thanks for letting me know anyway!
